name = "forvk"
version = "0.1.0"
license = "license"
author = "jordan4ibanez"
maintainer = "jordan4ibanez@users.noreply.github.com"
copyright = "Copyright 2024, jordan4ibanez"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

link = ["glfw", "vulkan"]

[dependencies]
fglm = { git = "https://github.com/jordan4ibanez/fglm" }
string_f90 = { git = "https://github.com/jordan4ibanez/string_f90" }
constants_f90 = { git = "https://github.com/jordan4ibanez/constants_f90" }
fortran_vector = { git = "https://github.com/jordan4ibanez/fortran_vector" }

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
